### ISSUE TITLE
Object Pose

### ISSUE THREAD

**Issue by DavidFernandezChaves** [NilsDengler/sem_mapping#1]
Hello!
We are working on a system similar to yours for the building of semantic maps and we would like to compare ourselves with you for a future contribution.

We are using your node "https://github.com/NilsDengler/sem_mapping/tree/master/Src/semmapping", but we are using a different CNN. For each detection of the CNN, we build the "cloud_and_boxes" message following your steps in the code of your CNN. In this sense, the bounding boxes are given w.r.t. the image plane (pixels in the image) while the point cloud is referenced w.r.t. the camera frame in 3D (coordinates in meters).

However, we get some strange results, where the objects are not well positioned and the bounding boxes sometimes do not come out square. 

Are we missing something? Are we wrong?

We would appreciate your help.

**Comment by NilsDengler** [comment]
Hi,
it's pretty hard to pinpoint the error from your description. However, here are 2 possible solutions:
1. Are you using an ApproximateTimeSynchronizer, as seen in my code, to match point cloud and RGB-image?
2. Do you match the RGB- with the Depth-image? If not, this could explain the incorrectly positioned objects. We have used "http://wiki.ros.org/depth_image_proc" for this

**Comment by DavidFernandezChaves** [comment]
We have already discovered the error. 
We sent the point cloud reference wrong.

Thank you!

**Comment by yani-rl-ai** [comment]
hi @DavidFernandezChaves which version of ROS do you use and how did you solve the error?
